In [3]:
import numpy as np

res, temp, tour, meal = np.loadtxt("cracker barrel.txt", skiprows=1, unpack=True)

x = np.column_stack((np.ones(res.size), res, temp, tour))

y = meal.reshape(-1, 1)

In [4]:
x

array([[ 1., 13., 33.,  9.],
       [ 1.,  2., 16.,  6.],
       [ 1., 14., 32.,  3.],
       [ 1., 23., 25.,  9.],
       [ 1., 13., 23.,  8.],
       [ 1., 13., 51.,  9.],
       [ 1.,  1., 27.,  7.],
       [ 1., 18., 16.,  2.],
       [ 1.,  7., 34.,  3.],
       [ 1., 10., 22.,  3.],
       [ 1., 26., 17.,  7.],
       [ 1.,  3., 21.,  1.],
       [ 1.,  3., 12.,  4.],
       [ 1., 21., 26.,  2.],
       [ 1., 22., 15.,  4.],
       [ 1.,  2., 21.,  7.],
       [ 1., 27., 18.,  3.],
       [ 1.,  6., 26.,  8.],
       [ 1., 10., 20.,  6.],
       [ 1., 18., 25.,  9.],
       [ 1., 15., 21., 10.],
       [ 1.,  9., 22.,  7.],
       [ 1., 26., 20.,  2.],
       [ 1.,  8., 21.,  1.],
       [ 1., 15., 12.,  7.],
       [ 1., 10., 14.,  9.],
       [ 1., 21., 19.,  4.],
       [ 1.,  5., 20.,  3.],
       [ 1.,  6., 18.,  3.],
       [ 1., 13., 23.,  4.]])

In [5]:
y

array([[52.],
       [17.],
       [46.],
       [70.],
       [43.],
       [60.],
       [23.],
       [43.],
       [28.],
       [31.],
       [65.],
       [15.],
       [15.],
       [59.],
       [52.],
       [22.],
       [68.],
       [34.],
       [30.],
       [56.],
       [50.],
       [36.],
       [68.],
       [25.],
       [38.],
       [30.],
       [56.],
       [19.],
       [19.],
       [41.]])

In [6]:
def predict(x, w):
    return np.matmul(x, w)

In [8]:
fake_weights = np.array([[0.1], [0.2], [0.3], [0.4]])

In [9]:
predict(x, fake_weights)

array([[16.2],
       [ 7.7],
       [13.7],
       [15.8],
       [12.8],
       [21.6],
       [11.2],
       [ 9.3],
       [12.9],
       [ 9.9],
       [13.2],
       [ 7.4],
       [ 5.9],
       [12.9],
       [10.6],
       [ 9.6],
       [12.1],
       [12.3],
       [10.5],
       [14.8],
       [13.4],
       [11.3],
       [12.1],
       [ 8.4],
       [ 9.5],
       [ 9.9],
       [11.6],
       [ 8.3],
       [ 7.9],
       [11.2]])

In [12]:
def loss(x, y, w):
    prediction = predict(x, y)
    return np.average((prediction - y) ** 2)

In [14]:
def gradient(x, y, w):
    return 2 * np.matmul(x.T, (predict(x, w) - y)) / x.shape[0]

In [15]:
gradient(x, y, fake_weights)

array([[  -57.8       ],
       [ -954.15333333],
       [-1318.12      ],
       [ -319.91333333]])

In [16]:
def train(x, y, iterations, lr):
    w = np.zeros((x.shape[1], 1))

    for i in range(iterations):
        print("Iteration %4d => Loss: %.20f" % (i, loss(x, y, w)))
        w -= gradient(x, y, w) * lr
    return w

In [18]:
w = train(x, y, 100000, 0.001)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 30 is different from 4)

In [ ]:
w